name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  php:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        php: [7.4, 7.3]
        dependency-version: [prefer-lowest, prefer-stable]

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: install dependencies
        run: composer update --${{ matrix.dependency-version }}

      - name: run tests
        run: composer test -- --coverage-clover=coverage.clover

      - name: upload code coverage
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover
